### PR TITLE
chore: update deps

### PR DESCRIPTION
**Pull request by snitin315**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [X] **metadata update**

### Motivation / Use-Case
update deps and lockfile.

### Breaking Changes
None

### Additional Info
I hope this will fix CI

### CODE REVIEW

**Comment by alexander-akait** [comment]
hm, all fine, just update tests

**Comment by snitin315** [comment]
@alexander-akait all tests are passing locally, nothing to update.

Screenshot 2021-07-13 at 6 21 56 PM

also passing for node 16 on CI - https://github.com/webpack-contrib/imports-loader/pull/104/checks?check_run_id=3056758162

Screenshot 2021-07-13 at 6 25 51 PM

**Comment by alexander-akait** [comment]
Try to do `rm -rf package-json.lock && npm i`, I think something with cache

**Comment by snitin315** [comment]
> Try to do `rm -rf package-json.lock && npm i`, I think something with cache

I tried it, still no luck. 
It could be a `cache` issue, removing following fixes it. -
 https://github.com/webpack-contrib/imports-loader/blob/df8284bc803909c5ef5b002b68f8183c2b0c5971/.github/workflows/nodejs.yml#L86

**Pull request merged**
